### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by bhmand** [WebucatorTraining/ssis-55321A#1]
Where are the ppt slides for the course?

**Comment by ndunn219** [comment]
The course does not come with PowerPoint slides. When we teach it, we sometimes present from the material itself, but most of the time, we spend presenting the tools and code taught in the course. The class is designed to use the **Try It** exercises in each chapter to teach the concepts presented in the chapter.

**Comment by bhmand** [comment]
Thank you for your reply. Sorry for asking but di you have a delivery guide? Are the students supposed to do the "try it exercises" in class or?

**Comment by ndunn219** [comment]
We do not. But yes, they are. If you have additional questions, please send them to the company from which you plan to purchase the courseware. Thanks.

**Comment by bhmand** [comment]
Thank for your reply. I will but I just thought that you were responsible for the course and courseware.

**Comment by ndunn219** [comment]
No worries. I am. This just is not the right forum. This repo is setup for feeding lab instructions, not for Q&A.

**Comment by bhmand** [comment]
Thats perfectly OK. But I am not able to find of information for any contact. So sorry that I am using this forum.
